version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - node
    environment:
      - NODE_ENV=production
    restart: always

  node:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
