export const configEditor = {
  zIndex: 0,
  readonly: false,
  activeButtonsInReadOnly: ["source", "fullsize", "print", "about"],
  toolbarButtonSize: "middle",
  theme: "default",
  enableDragAndDropFileToEditor: true,
  saveModeInCookie: false,
  spellcheck: true,
  editorCssclassName: false,
  triggerChangeEvent: true,
  height: 1000,
  direction: "ltr",
  language: "en",
  debugLanguage: false,
  i18n: "en",
  tabIndex: -1,
  toolbar: true,
  enter: "P",
  useSplitMode: false,
  colorPickerDefaultTab: "background",
  imageDefaultWidth: 100,
  removeButtons: [
    "source",
    "about",
    "outdent",
    "indent",
    "print",
    "table",
    "superscript",
    "subscript",
    "file",
    "cut",
    "selectall",
  ],
  disablePlugins: ["paste", "stat"],
  events: {},
  textIcons: false,
  uploader: {
    insertImageAsBase64URI: true,
  },
  placeholder: "",
  showXPathInStatusbar: false,
};
